name: habitly
description: "Habitly App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.5
  uuid: ^4.2.1
  intl: ^0.19.0
  firebase_core: ^3.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
